# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10763edad138b4f414be37ebf91db9bf3afbcdf917076f173368f1532e3053c5367c669671d516350c9e47a61e86045118d2c87b126bb4a7f0125d4674d7aaa3

test:
  secret_key_base: 46fe2369fcb86440a6ac19e1f549f953b4a55dafe303fc767b40be02a65ffa5d800c7ab70b87e2ea029d4ec5f16a182107667c63425b1d03e2cbbc3605487c6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
